[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "themis"
version = "0.1.0"
requires-python = ">=3.8"

[project.scripts]
themis = "themis.cli:main"  

[tool.setuptools]
packages = ["themis*", "themis_scripts*"]
